# 应用名称
APP_NAME: SKYGO
# 环境:支持local,testing,production
APP_ENV: production
# 是否开启调试模式
APP_DEBUG: false
# 加密密钥
APP_KEY: "xxxxxxx"
# 时区 , 数据库要%2F , time.LoadLocation 要 xx/xx
TIMEZONE: "UTC"
# 服务host，port，url
HTTP_HOST: "0.0.0.0"
HTTP_PORT: 7001
HTTP_CONNECT: "0.0.0.0:7001"
HTTP_CONNECT_URL: "http://0.0.0.0:7001"



# 数据库配置
DB_HOST: "127.0.0.1"
DB_PORT: 3308
DB_USERNAME: "root"
DB_PASSWORD: "123456"
DB_DATABASE: "demo"
DB_CHARSET: "utf8mb4"
DB_MAX_OPEN_CONNS: 100
DB_MAX_IDLE_CONNS: 10
DB_MAX_LIFE_SECONDS: 300
DB_SQL_LOG: false

# redis配置
REDIS_HOST: "127.0.0.1"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""
# 非cache场景使用，会话等不能清楚
REDIS_DB: 1
# cache专用， 应当可以清楚（谨慎flushdb)
REDIS_CACHE_DB: 0

# tode 测试   日志写入级别
LOG_LEVEL: "error"
