// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"gosky/app/services/user"
)

// Injectors from wire.go:

func UserService() *user.UserService {
	userService := user.NewUserService()
	return userService
}

// wire.go:

var SuperSet = wire.NewSet(user.NewUserService)
